language: node_js
node_js:
  - "6"
  - "5"
  - "4"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database mpro;' -U postgres
  - 'export NODE_ENV=test'
  - 'npm install'
notifications:
  slack: ovdinfo:pC2a1JMfPsjs3hKPAzz7yPUB